name: 'Get Bitwarden Secrets'
description: 'Retrieve secrets from Bitwarden Secrets Manager'

inputs:
  access_token:
    description: 'Bitwarden Secrets Manager access token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Bitwarden Secrets Manager CLI
      shell: bash
      run: |
        curl -L "https://github.com/bitwarden/sdk/releases/download/bws-v0.3.0/bws-x86_64-unknown-linux-gnu-0.3.0.zip" -o bws.zip
        unzip bws.zip
        chmod +x bws
        sudo mv bws /usr/local/bin/
        rm bws.zip

    - name: Get secrets
      shell: bash
      env:
        BWS_ACCESS_TOKEN: ${{ inputs.access_token }}
      run: |
        # List all secrets and process them into environment variables
        bws secret list --output env >> $BWS_SECRET